### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by mikepc** [cdiniz/play-slick-oauth2#2]
Hello there :-) I am new to Scala/Play, but I would love to use this as a boilerplate to start an auth service (coming from .NET/NodeJS/Go). I'm getting the above error when I activator run and I'm kind of lost on where I can make the appropriate updates myself.

**Comment by cdiniz** [comment]
Hi Mike! It seems something with your java version. I have "1.8.0_91" and I can make activator run or sbt run. Could you check if [this](https://github.com/typesafehub/config/issues/321) helps you to run the template in your machine?

**Comment by vickyi** [comment]
use this：
        <dependency>
            <groupId>com.typesafe</groupId>
            <artifactId>config</artifactId>
            <version>1.2.1</version>
        </dependency>

**Comment by vickyi** [comment]
use this:
```
        <dependency>
            <groupId>com.typesafe</groupId>
            <artifactId>config</artifactId>
            <version>1.2.1</version>
        </dependency>
```

**Comment by vickyi** [comment]
Version 1.2.1 and earlier were built for Java 6 and Java 7, use this:
```
        <dependency>
            <groupId>com.typesafe</groupId>
            <artifactId>config</artifactId>
            <version>1.2.1</version>
        </dependency>
```
while newer versions (1.3.0 and above) will be built for Java 8.

You can find published releases on Maven Central.
```
    <dependency>
        <groupId>com.typesafe</groupId>
        <artifactId>config</artifactId>
        <version>1.3.1</version>
    </dependency>
```
sbt dependency:
```
    libraryDependencies += "com.typesafe" % "config" % "1.3.1"
```
