### ISSUE TITLE
What role does this app play in OAuth, client or server?

### ISSUE THREAD

**Issue by asarkar** [cdiniz/play-slick-oauth2#3]
Is this a seed for an OAuth server or an OAuth client, like if I want to integrate with Facebook?

**Comment by cdiniz** [comment]
Hi. It's server-side.

**Comment by asarkar** [comment]
@cdiniz, thanks, would you have any pointers for an OAuth client with Play? I'm mostly interested in seeing how a filter might look like.

**Comment by cdiniz** [comment]
You could take a look at https://github.com/mohiva/play-silhouette
